"""T-25..T-31: optional inbound authentication and listener TLS.

The relay is unauthenticated by default. These cover the opt-in mode that lets an
operator narrow `mynetworks` and require credentials from every client, which is
the only in-container defence against a compromised pod in the same namespace.
"""

from __future__ import annotations

import smtplib
import ssl
import subprocess
import time

import pytest

from conftest import AUTH_DOMAIN, docker, message

USER = "app1"
SECRET = "hunter2xyzverysecret"


@pytest.fixture
def listener_certs(tmp_path):
    """A self-signed certificate for the relay's own listener.

    Deliberately generated by the TEST, not by the image. The image only ever
    mounts a certificate: generating one at startup would force every client to
    disable verification, which teaches people to accept any certificate.
    """
    out = tmp_path / "listener"
    out.mkdir()
    docker(
        "run", "--rm", "-v", f"{out}:/out", "alpine:3.24", "sh", "-c",
        "apk add --no-cache -q openssl && openssl req -x509 -newkey rsa:2048 -nodes -days 3650 "
        "-subj '/CN=mailkube-relay' -keyout /out/tls.key -out /out/tls.crt && chmod 644 /out/tls.*",
    )
    return out


def _auth_probe(relay, user: str, password: str) -> str:
    """Run an AUTH PLAIN exchange inside the container and return the reply code."""
    script = (
        f'A=$(printf "\\0{user}\\0{password}" | base64 | tr -d "\\n"); '
        '(sleep 0.4; printf "EHLO t\\r\\n"; sleep 0.4; '
        'printf "AUTH PLAIN %s\\r\\n" "$A"; sleep 0.6; printf "QUIT\\r\\n") '
        f'| nc -w 5 127.0.0.1 {relay_port(relay)}'
    )
    out = relay.exec("sh", "-c", script, check=False).stdout
    for line in out.replace("\r", "").splitlines():
        if line[:3] in {"235", "535", "530", "538", "503"}:
            return line[:3]
    return "???"


def relay_port(relay) -> str:
    return "25"


# --------------------------------------------------------------------------- #
#  Default posture
# --------------------------------------------------------------------------- #
def test_t25_auth_is_off_by_default(pair):
    """The relay stays unauthenticated unless accounts are configured."""
    _, relay = pair
    assert relay.postconf_one("smtpd_sasl_auth_enable") == "no"
    assert relay.postconf_one("smtpd_client_restrictions") == "permit_mynetworks, reject"


# --------------------------------------------------------------------------- #
#  Optional authentication
# --------------------------------------------------------------------------- #
def test_t26_accounts_enable_sasl_and_accept_the_right_password(factory):
    factory.sink()
    relay = factory.relay(RELAY_AUTH_USERS=f"{USER}:{SECRET}")

    assert relay.postconf_one("smtpd_sasl_auth_enable") == "yes"
    assert "permit_sasl_authenticated" in relay.postconf_one("smtpd_client_restrictions")
    assert _auth_probe(relay, USER, SECRET) == "235"


def test_t26b_wrong_password_is_rejected(factory):
    factory.sink()
    relay = factory.relay(RELAY_AUTH_USERS=f"{USER}:{SECRET}")
    assert _auth_probe(relay, USER, "definitely-not-it") == "535"


def test_t27_realm_survives_a_restart(factory):
    """Regression: the SASL realm must not be the container hostname.

    Cyrus keys entries as user@realm. With no explicit realm, saslpasswd2
    defaults to the machine hostname, which in a container is a random ID that
    changes on every start. That yields a database whose keys never match what
    Postfix looks up: AUTH is advertised and every attempt fails 535, and it
    only shows up after a restart. The realm is pinned to $myhostname, which is
    derived from the authenticated domain and therefore stable.
    """
    factory.sink()
    relay = factory.relay(RELAY_AUTH_USERS=f"{USER}:{SECRET}")
    assert _auth_probe(relay, USER, SECRET) == "235"

    docker("restart", relay.name)
    # Probed from inside: some Docker runtimes do not re-establish the host port
    # forward after a restart, which would fail this test for the wrong reason.
    assert relay.wait_ready_internal(), "relay did not come back up"
    time.sleep(2)

    listed = relay.exec("sasldblistusers2", "-f", "/run/postfix/sasldb2", check=False).stdout
    assert f"{USER}@{relay.postconf_one('myhostname')}" in listed, f"realm drifted: {listed!r}"
    assert _auth_probe(relay, USER, SECRET) == "235", "authentication broke after a restart"


def test_t28_accounts_can_come_from_a_mounted_file(factory, tmp_path):
    """The shape a Kubernetes Secret should use."""
    f = tmp_path / "accounts"
    f.write_text(f"# one account per line\n{USER}:{SECRET}\napp2:anothersecret\n")
    factory.sink()
    relay = factory.relay(
        RELAY_AUTH_USERS_FILE="/run/secrets/accounts",
        extra_args=["-v", f"{f}:/run/secrets/accounts:ro"],
    )
    assert "2 account(s)" in relay.logs()
    assert _auth_probe(relay, USER, SECRET) == "235"
    assert _auth_probe(relay, "app2", "anothersecret") == "235"


# --------------------------------------------------------------------------- #
#  Required authentication
# --------------------------------------------------------------------------- #
def test_t29_required_auth_rejects_an_unauthenticated_sender(factory):
    """A client on the docker bridge is inside the default mynetworks.

    With RELAY_AUTH_REQUIRED=yes, permit_mynetworks is dropped, so being on a
    private network is no longer enough.
    """
    factory.sink()
    relay = factory.relay(RELAY_AUTH_USERS=f"{USER}:{SECRET}", RELAY_AUTH_REQUIRED="yes")
    assert relay.postconf_one("smtpd_client_restrictions") == (
        "permit_inet_interfaces, permit_sasl_authenticated, reject"
    )

    with pytest.raises(smtplib.SMTPException):
        relay.send(message(subject="should be refused"))


def test_t29b_required_auth_accepts_an_authenticated_sender(factory):
    sink = factory.sink()
    relay = factory.relay(RELAY_AUTH_USERS=f"{USER}:{SECRET}", RELAY_AUTH_REQUIRED="yes")

    with smtplib.SMTP("127.0.0.1", relay.port, timeout=20) as s:
        s.login(USER, SECRET)
        s.send_message(message(subject="authenticated send"))

    msgs = sink.wait_for_messages(1)
    assert len(msgs) == 1, "an authenticated client must be able to send"


# --------------------------------------------------------------------------- #
#  Listener TLS
# --------------------------------------------------------------------------- #
def test_t30_tls_makes_auth_conditional_on_starttls(factory, listener_certs):
    sink = factory.sink()
    relay = factory.relay(
        RELAY_AUTH_USERS=f"{USER}:{SECRET}",
        RELAY_AUTH_REQUIRED="yes",
        RELAY_TLS_CERT_FILE="/tls/tls.crt",
        RELAY_TLS_KEY_FILE="/tls/tls.key",
        extra_args=["-v", f"{listener_certs}:/tls:ro"],
    )
    assert relay.postconf_one("smtpd_tls_security_level") == "encrypt"
    assert relay.postconf_one("smtpd_tls_auth_only") == "yes"

    # Credentials must not be accepted before the channel is encrypted.
    assert _auth_probe(relay, USER, SECRET) == "530"

    # ... and must work after STARTTLS.
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    with smtplib.SMTP("127.0.0.1", relay.port, timeout=20) as s:
        s.starttls(context=ctx)
        s.login(USER, SECRET)
        s.send_message(message(subject="authenticated over TLS"))

    assert len(sink.wait_for_messages(1)) == 1


def test_t30b_healthcheck_survives_mandatory_tls(factory, listener_certs):
    """`encrypt` refuses mail commands before STARTTLS, but the banner and QUIT
    are still allowed, which is all the probe uses. If this regresses, every
    deployment with listener TLS flaps."""
    factory.sink()
    relay = factory.relay(
        RELAY_TLS_CERT_FILE="/tls/tls.crt",
        RELAY_TLS_KEY_FILE="/tls/tls.key",
        extra_args=["-v", f"{listener_certs}:/tls:ro"],
    )
    assert relay.exec("/usr/local/bin/healthcheck.sh", check=False).returncode == 0


# --------------------------------------------------------------------------- #
#  Validation
# --------------------------------------------------------------------------- #
def test_t31_required_without_accounts_is_refused(factory):
    """Otherwise every client, including the healthcheck, would be rejected."""
    p = factory.run_to_completion(
        SMTP_USERNAME=f"myapp01@{AUTH_DOMAIN}", SMTP_PASSWORD="x", RELAY_AUTH_REQUIRED="yes"
    )
    assert p.returncode != 0
    assert "no accounts are configured" in (p.stdout + p.stderr)


def test_t31b_malformed_account_list_is_refused(factory):
    p = factory.run_to_completion(
        SMTP_USERNAME=f"myapp01@{AUTH_DOMAIN}", SMTP_PASSWORD="x", RELAY_AUTH_USERS="nopasswordhere"
    )
    assert p.returncode != 0
    assert "user:password" in (p.stdout + p.stderr)


def test_t31c_tls_cert_without_key_is_refused(factory):
    p = factory.run_to_completion(
        SMTP_USERNAME=f"myapp01@{AUTH_DOMAIN}", SMTP_PASSWORD="x", RELAY_TLS_CERT_FILE="/tls/tls.crt"
    )
    assert p.returncode != 0
    assert "must be set together" in (p.stdout + p.stderr)


def test_t31d_auth_without_tls_warns(factory):
    """Passwords in the clear are a deliberate choice, never an accident."""
    factory.sink()
    relay = factory.relay(RELAY_AUTH_USERS=f"{USER}:{SECRET}")
    logs = relay.logs()
    assert "no TLS certificate" in logs
    assert "base64-encoded, not encrypted" in logs
